from por_copiar.utilidades import ContenidoPedidos, Locales, Pedidos, Pizzas

RESULTADO_CONSULTA_ANIDADA_0=[Pizzas(nombre='Pepinillos y Tocino_S', ingredientes='pepinillos;tocino;queso;salsa de cebolla', precio=9420), Pizzas(nombre='Pepinillos y Tocino_M', ingredientes='pepinillos;tocino;queso;salsa de cebolla', precio=10537), Pizzas(nombre='Pepinillos y Tocino_L', ingredientes='pepinillos;tocino;queso;salsa de cebolla', precio=15191), Pizzas(nombre='Carnívora BBQ_S', ingredientes='carne molida;salchicha;tocino;queso;salsa BBQ', precio=7900), Pizzas(nombre='Carnívora BBQ_M', ingredientes='carne molida;salchicha;tocino;queso;salsa BBQ', precio=11051), Pizzas(nombre='Carnívora BBQ_L', ingredientes='carne molida;salchicha;tocino;queso;salsa BBQ', precio=17194)]
RESULTADO_CONSULTA_ANIDADA_1=[Pizzas(nombre='Palta y Tomate_S', ingredientes='palta;tomate cherry;queso;salsa de tomate', precio=7718)]
RESULTADO_CONSULTA_ANIDADA_2=13738
RESULTADO_CONSULTA_ANIDADA_3=[Pizzas(nombre='Pepinillos y Tocino_S', ingredientes='pepinillos;tocino;queso;salsa de cebolla', precio=9420), Pizzas(nombre='Pepinillos y Tocino_M', ingredientes='pepinillos;tocino;queso;salsa de cebolla', precio=10537), Pizzas(nombre='Pepinillos y Tocino_L', ingredientes='pepinillos;tocino;queso;salsa de cebolla', precio=15191), Pizzas(nombre='Queso de Cabra y Pimientos_S', ingredientes='queso de cabra;pimiento;queso;salsa de pimentón', precio=9843), Pizzas(nombre='Queso de Cabra y Pimientos_M', ingredientes='queso de cabra;pimiento;queso;salsa de pimentón', precio=10805), Pizzas(nombre='Queso de Cabra y Pimientos_L', ingredientes='queso de cabra;pimiento;queso;salsa de pimentón', precio=18098), Pizzas(nombre='Pimienta y Jamón_S', ingredientes='jamón;queso;salsa de pimienta', precio=8398), Pizzas(nombre='Pimienta y Jamón_M', ingredientes='jamón;queso;salsa de pimienta', precio=13090), Pizzas(nombre='Pimienta y Jamón_L', ingredientes='jamón;queso;salsa de pimienta', precio=18819)]
RESULTADO_CONSULTA_ANIDADA_4=129354
RESULTADO_CONSULTA_ANIDADA_5=1964
RESULTADO_CONSULTA_ANIDADA_6=[Pizzas(nombre='Radiante Sabroso Aromático con Cuidado_S', ingredientes='tocino;camarones;salsa de queso', precio=9566), Pizzas(nombre='Brillante Maravilloso Encantador con Arte_S', ingredientes='Dedos Chamuscados;Corazón Desgarrado;Baba de Zombie;jamón;tocino;salsa BBQ', precio=9663), Pizzas(nombre='Magnífico Tierno Jugoso con Ingenio_S', ingredientes='Sesos Picados;tocino;pepperoni;Corazón Desgarrado;salsa de pimentón', precio=9594)]
RESULTADO_CONSULTA_ANIDADA_7=[Pizzas(nombre='Asombroso Apetitoso Aromático con Belleza_S', ingredientes='Baba de Zombie;aceitunas negras;carne molida;Dedos de Cadáver;salsa de mostaza', precio=9403), Pizzas(nombre='Asombroso Apetitoso Aromático con Belleza_M', ingredientes='Baba de Zombie;aceitunas negras;carne molida;Dedos de Cadáver;salsa de mostaza', precio=10813), Pizzas(nombre='Asombroso Apetitoso Aromático con Belleza_L', ingredientes='Baba de Zombie;aceitunas negras;carne molida;Dedos de Cadáver;salsa de mostaza', precio=17951), Pizzas(nombre='Tradicional Asombroso Brillante con Esmero_S', ingredientes='albahaca;Baba de Zombie;queso de cabra;aceitunas negras;Pulmones Fritos;salsa de mostaza', precio=9917), Pizzas(nombre='Tradicional Asombroso Brillante con Esmero_M', ingredientes='albahaca;Baba de Zombie;queso de cabra;aceitunas negras;Pulmones Fritos;salsa de mostaza', precio=10858), Pizzas(nombre='Tradicional Asombroso Brillante con Esmero_L', ingredientes='albahaca;Baba de Zombie;queso de cabra;aceitunas negras;Pulmones Fritos;salsa de mostaza', precio=15109), Pizzas(nombre='Magnífico Alegre Jugoso con Belleza_S', ingredientes='Cerebro con Queso;queso;pera;tomate;salsa de pimentón', precio=9825), Pizzas(nombre='Magnífico Alegre Jugoso con Belleza_M', ingredientes='Cerebro con Queso;queso;pera;tomate;salsa de pimentón', precio=13183), Pizzas(nombre='Magnífico Alegre Jugoso con Belleza_L', ingredientes='Cerebro con Queso;queso;pera;tomate;salsa de pimentón', precio=15257), Pizzas(nombre='Crujiente Picante Crujiente con Alegría_S', ingredientes='Carne Podrida;Dedos de Cadáver;piña;salsa de queso', precio=8292), Pizzas(nombre='Crujiente Picante Crujiente con Alegría_M', ingredientes='Carne Podrida;Dedos de Cadáver;piña;salsa de queso', precio=11062), Pizzas(nombre='Crujiente Picante Crujiente con Alegría_L', ingredientes='Carne Podrida;Dedos de Cadáver;piña;salsa de queso', precio=17846), Pizzas(nombre='Magnífico Suave Sensacional con Belleza_S', ingredientes='queso azul;salchicha;aceitunas negras;champiñones;salsa de pimienta', precio=7060), Pizzas(nombre='Magnífico Suave Sensacional con Belleza_M', ingredientes='queso azul;salchicha;aceitunas negras;champiñones;salsa de pimienta', precio=11030), Pizzas(nombre='Magnífico Suave Sensacional con Belleza_L', ingredientes='queso azul;salchicha;aceitunas negras;champiñones;salsa de pimienta', precio=15841), Pizzas(nombre='Vibrante Vibrante Increíble con Originalidad_S', ingredientes='queso azul;Corazón Desgarrado;Salsa de Queso;choclo;salsa de tomate', precio=8416), Pizzas(nombre='Vibrante Vibrante Increíble con Originalidad_M', ingredientes='queso azul;Corazón Desgarrado;Salsa de Queso;choclo;salsa de tomate', precio=10985)]
